# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Keepin_iOSArchive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keepin_iOSArchive
	pod 'Alamofire', '~> 5.4'
  	pod 'Kingfisher', '~> 6.0'
end
